volumes:
  pg_data:

services:
  postgres:
    image: postgres:16-alpine3.21
    restart: always
    command: >
      --log_statement=all
    ports:
      - "25432:5432"
    volumes:
      - "pg_data:/var/lib/postgresql/data"
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
